
qa_dict = {
    "I am playing cricket": "Cricket is being played by me",
    "He played many games": "Many games were played by him",
    "He had already passed the examination": "The examination had already been passed by him",
    "A child likes toys": "Toys are liked by a child",
    "She is eating mangoes": "Mangoes are being eaten by her",
    "I saw him last evening": "He was seen by me last evening",
    "She had milked the cow": "The cow had been milked by her",
    "The two teams were playing the match": "The match was being played by the two teams",
    "I have read the book": "The book has been read by me",
    "The postman delivers letters": "Letters are delivered by the postman",
    "She has written letters": "Letters have been written by her",
    "The doctor had examined him": "He had been examined by the doctor",
    "I saw a snake": "A snake was seen by me",
    "I was making a plan": "A plan was being made by me",
    "They help her": "She is helped by them",
    "They were singing songs": "Songs were being sung by them",
    "Siva guides me": "I am guided by Siva",
    "I have not tasted the food": "The food has not been tasted by me",
    "He did not ring the bell": "The bell was not rung by him",
    "I do not use soap": "Soap is not used by me",
    "We are playing chess?": "Is chess being played by us?",
    "Suganya can help me": "Can I be helped by Suganya",
    "I ate a mango": "A mango was eaten by me",
    "My father will advise you": "You will be advised by your father",
    "Did she write a story?": "Was a story written by her?",
    "I was taking coffee": "Coffee was being taken by me",
    "Who saw the thief?": "By whom was the thief seen?",
    "Does he help the poor?": "Are the poor helped by him?",
    "She wrote some letters.": "Some letters were written by her",
    "My mother loves me": "I am loved by my mother",
    "The school gave him many prizes": "He was given many prizes by the school",
    "I know your father": "Your father is known to me",
    "I will spend all the money": "All the money will be spent by me",
    "They can help Shalini": "Shalini can be helped by them",
    "Who stole your pen?": "By whom was your pen stolen?",
    "She was taking milk": "Milk was being taken by her",
    "She missed the Cheran Express": "The Cheran Express was missed by her",
    "I can teach Suganya": "Suganya can be taught by me",
    "My friend is helping me": "I am being helped by my friend",
    "Inform the police": "Let the police be informed",
    "The boy is flying a kite": "A kite is being flown by the boy",
    "When did you lose your book?": "When was your book lost by you?",
    "How can we help you?": "How can you be helped by us?",
    "He has helped this child": "This child has been helped by him",
    "I eat fresh vegetables": "Fresh vegetables are eaten by me",
    "They will arrange a variety programme": "A variety programme will be arranged by them",
    "I ate mangoes": "Mangoes were eaten by me",
    "She is calling me": "I am being called by her",
    "She does not like tea": "Tea is not liked by her",
    "Mr Anand teaches us science": "We are taught science by Mr Anand",
    "I heard Mukesh once": "Mukesh was heard by me once",
    "He hates bad people": "Bad people are hated by him",
    "Was the servant bringing tea?": "Was tea being brought by the servant?",
    "I was writing an essay": "An essay was being written by me",
    "She looks after the child": "The child is looked after by her",
    "He could not lift the box": "The box could not be lifted by him",
    "She had cooked some dishes": "Some dishes had been cooked by her",
    "Please help me": "You are requested to help me",
    "We can teach you": "You can be taught by us",
    "She has taught him": "He has been taught by her",
    "I like him": "He is liked by me",
    "You can help us": "We can be helped by you",
    "He has helped these children": "These children have been helped by him",
    "They were helping you": "You were being helped by them",
    "She has taught them": "They have been taught by her",
    "Open the window": "Let the window be opened",
    "He helps me": "I am helped by him",
    "Do you imitate others?": "Are others imitated by you?",
    "They fund schools for girls": "Schools for girls are funded by them",
    "Women like men to flatter them": "Women like to be flattered by men",
    "She makes cakes every Sunday": "Cakes are made by her every Sunday",
    "The telegraph wires have been cut": "Someone has cut the telegraph wires",
    "Did he complete the report on time?": "Was the report completed by him on time?",
    "Has she been writing the letters properly?": "Have the letters been being written by her properly?",
    "Will they deliver the packages tomorrow?": "Will the packages be delivered by them tomorrow?",
    "Was he painting the wall carefully?": "Was the wall being painted carefully by him?",
    "Had they solved the puzzle before sunset?": "Had the puzzle been solved by them before sunset?",
    "Is he designing the new website now?": "Is the new website being designed by him now?",
    "Were they building the bridge last year?": "Was the bridge being built by them last year?",
    "Shall we announce the results today?": "Shall the results be announced by us today?",
    "Do the workers clean the factory every week?": "Is the factory cleaned by the workers every week?",
    "Had she been preparing the documents for hours?": "Had the documents been being prepared by her for hours?",
    "Does the chef cook the dishes quickly?": "Are the dishes cooked quickly by the chef?",
    "Has the scientist discovered the new element yet?": "Has the new element been discovered by the scientist yet?",
    "Were they chasing the thief through the alley?": "Was the thief being chased through the alley by them?",
    "Will the manager have approved the project by Monday?": "Will the project have been approved by the manager by Monday?",
    "Is she sending the invitations today?": "Are the invitations being sent by her today?",
    "Have they been fixing the broken machines?": "Have the broken machines been being fixed by them?",
    "Did the students submit the assignments late?": "Were the assignments submitted late by the students?",
    "Was the committee reviewing the applications yesterday?": "Were the applications being reviewed by the committee yesterday?",
    "Will he have been writing the novel for a year by next month?": "Will the novel have been being written by him for a year by next month?",
    "Do the engineers test the prototypes regularly?": "Are the prototypes tested regularly by the engineers?"
}

