reversed_qa_dict = {
    "Are the prototypes tested regularly by the engineers?": "Do the engineers test the prototypes regularly?",
    "Will the novel have been being written by him for a year by next month?": "Will he have been writing the novel for a year by next month?",
    "Were the applications being reviewed by the committee yesterday?": "Was the committee reviewing the applications yesterday?",
    "Were the assignments submitted late by the students?": "Did the students submit the assignments late?",
    "Have the broken machines been being fixed by them?": "Have they been fixing the broken machines?",
    "Are the invitations being sent by her today?": "Is she sending the invitations today?",
    "Will the project have been approved by the manager by Monday?": "Will the manager have approved the project by Monday?",
    "Was the thief being chased through the alley by them?": "Were they chasing the thief through the alley?",
    "Has the new element been discovered by the scientist yet?": "Has the scientist discovered the new element yet?",
    "Are the dishes cooked quickly by the chef?": "Does the chef cook the dishes quickly?",
    "Had the documents been being prepared by her for hours?": "Had she been preparing the documents for hours?",
    "Is the factory cleaned by the workers every week?": "Do the workers clean the factory every week?",
    "Shall the results be announced by us today?": "Shall we announce the results today?",
    "Was the bridge being built by them last year?": "Were they building the bridge last year?",
    "Is the new website being designed by him now?": "Is he designing the new website now?",
    "Had the puzzle been solved by them before sunset?": "Had they solved the puzzle before sunset?",
    "Was the wall being painted carefully by him?": "Was he painting the wall carefully?",
    "Will the packages be delivered by them tomorrow?": "Will they deliver the packages tomorrow?",
    "Have the letters been being written by her properly?": "Has she been writing the letters properly?",
    "Was the report completed by him on time?": "Did he complete the report on time?",
    "The telegraph wires have been cut": "Someone has cut the telegraph wires",
    "Cakes are made by her every Sunday": "She makes cakes every Sunday",
    "Women like to be flattered by men": "Women like men to flatter them",
    "Schools for girls are funded by them": "They fund schools for girls",
    "Are others imitated by you?": "Do you imitate others?",
    "I am helped by him": "He helps me",
    "Let the window be opened": "Open the window",
    "They have been taught by her": "She has taught them",
    "You were being helped by them": "They were helping you",
    "These children have been helped by him": "He has helped these children",
    "We can be helped by you": "You can help us",
    "He is liked by me": "I like him",
    "He has been taught by her": "She has taught him",
    "You can be taught by us": "We can teach you",
    "You are requested to help me": "Please help me",
    "Some dishes had been cooked by her": "She had cooked some dishes",
    "The box could not be lifted by him": "He could not lift the box",
    "The child is looked after by her": "She looks after the child",
    "An essay was being written by me": "I was writing an essay",
    "Was tea being brought by the servant?": "Was the servant bringing tea?",
    "Bad people are hated by him": "He hates bad people",
    "Mukesh was heard by me once": "I heard Mukesh once",
    "We are taught science by Mr Anand": "Mr Anand teaches us science",
    "Tea is not liked by her": "She does not like tea",
    "I am being called by her": "She is calling me",
    "Mangoes were eaten by me": "I ate mangoes",
    "A variety programme will be arranged by them": "They will arrange a variety programme",
    "Fresh vegetables are eaten by me": "I eat fresh vegetables",
    "This child has been helped by him": "He has helped this child",
    "How can you be helped by us?": "How can we help you?",
    "When was your book lost by you?": "When did you lose your book?",
    "A kite is being flown by the boy": "The boy is flying a kite",
    "Let the police be informed": "Inform the police",
    "I am being helped by my friend": "My friend is helping me",
    "Suganya can be taught by me": "I can teach Suganya",
    "The Cheran Express was missed by her": "She missed the Cheran Express",
    "Milk was being taken by her": "She was taking milk",
    "By whom was your pen stolen?": "Who stole your pen?",
    "Shalini can be helped by them": "They can help Shalini",
    "All the money will be spent by me": "I will spend all the money",
    "Your father is known to me": "I know your father",
    "He was given many prizes by the school": "The school gave him many prizes",
    "I am loved by my mother": "My mother loves me",
    "Some letters were written by her": "She wrote some letters.",
    "Are the poor helped by him?": "Does he help the poor?",
    "By whom was the thief seen?": "Who saw the thief?",
    "Coffee was being taken by me": "I was taking coffee",
    "Was a story written by her?": "Did she write a story?",
    "You will be advised by your father": "My father will advise you",
    "A mango was eaten by me": "I ate a mango",
    "Can I be helped by Suganya": "Suganya can help me",
    "Is chess being played by us?": "We are playing chess?",
    "Soap is not used by me": "I do not use soap",
    "The bell was not rung by him": "He did not ring the bell",
    "The food has not been tasted by me": "I have not tasted the food",
    "I am guided by Siva": "Siva guides me",
    "Songs were being sung by them": "They were singing songs",
    "She is helped by them": "They help her",
    "A plan was being made by me": "I was making a plan",
    "A snake was seen by me": "I saw a snake",
    "He had been examined by the doctor": "The doctor had examined him",
    "Letters have been written by her": "She has written letters",
    "Letters are delivered by the postman": "The postman delivers letters",
    "The book has been read by me": "I have read the book",
    "The match was being played by the two teams": "The two teams were playing the match",
    "The cow had been milked by her": "She had milked the cow",
    "He was seen by me last evening": "I saw him last evening",
    "Mangoes are being eaten by her": "She is eating mangoes",
    "Toys are liked by a child": "A child likes toys",
    "The examination had already been passed by him": "He had already passed the examination",
    "Many games were played by him": "He played many games",
    "Cricket is being played by me": "I am playing cricket"
}
